project:
  type: website

website:
  title: "ISSS626-GAA"
  navbar:
    left:
      - text: "Hands-on Exercise" 
        menu:
          - text: "Hands-on Exercise 1A"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "Hands-on Exercise 1B"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01B.html" 
          - text: "Hands-on Exercise 2A"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02A.html"
          - text: "Hands-on Exercise 2B"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02B.html"   
          - text: "Hands-on Exercise 3"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
          - text: "Hands-on Exercise 4"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html"
      - text: "In-class Exercise" 
        menu:
          - text: "In-class Exercise 1"
            href: "In-class_EX/In-class_EX01/In-class_EX01.html"
          - text: "In-class Exercise 2"
            href: "In-class_EX/In-class_EX02/In-class_EX02.html"
          - text: "In-class Exercise 3"
            href: "In-class_EX/In-class_EX03/In-class_EX03.html"  
      - text: "Take-home Exercise" 
        menu:
          - text: "Take home exercise 1"
            href: "Take_home_Ex/Take_home_Ex01/Take_home_Ex01.html"
            

    right:
      - href: index.qmd
        text: Home
      - about.qmd

format: 
  html:
    theme: solar
    css: styles.css
    toc: true

editor: visual
