---
title: "In-class Exercise 06"
author: "yang yayong"
date: "Sep 30 2024"
date-modified: "last-modified"
execute:
  eval: true
  echo: true
  message: false
  freeze: true
---

```{r}
pacman::p_load(sf, sfdep, tmap, tidyverse)
```

```{r}
hunan <- st_read(dsn = "data/geospatial", 
                 layer = "Hunan")
```

```{r}
GDPPC <- read_csv("data/aspatial/Hunan_GDPPC.csv")

```

```{r}
# Create a space-time cube object  #each time have a layer
GDPPC_st <- spacetime(GDPPC, hunan,
                       .loc_col = "County",#space indicator
                       .time_col = "Year")  #time  integer 
```

```{r}
# Check if it is a space-time cube object
is_spacetime_cube(GDPPC_st)
```

inverse distance weights(g\* should be included itself)

```{r}
# Compute Gi* statistic
# Get neighbors and derive spatial weights
GDPPC_nb <- GDPPC_st %>%
  activate("geometry") %>%  #must have this to compute 
  mutate(nb = include_self(
           st_contiguity(geometry)),#how many neighbour
         wt = st_inverse_distance(nb, 
                                  geometry, 
                                  scale = 1,
                                  alpha = 1),
  .before = 1) %>% #infront of the table
  set_nbs("nb") %>% #
  set_wts("wt")
```

```{r}
gi_stars <- GDPPC_nb %>%
  group_by(Year) %>%
  mutate(gi_star = local_gstar_perm(
    GDPPC, nb, wt)) %>%
  tidyr::unnest(gi_star)
```

this have trend ,moran may not have trend

```{r}
cbg <- gi_stars %>%
  ungroup() %>%
  filter(County == "Changsha") %>%
  select(County, Year, gi_star)
```

```{r}
ggplot(data = cbg, aes(x = Year, y = gi_star)) +
  geom_line() +
  theme_light()
```

```{r}
#| eval: false
cbg %>%
  summarise(mk = list(
    unclass(
      kendall::Mannkendall(gi_star)
    )
  )) %>%
  tidyr::unnest_wider(mk)

```

```{r}
ehsa <- gi_stars %>%
  group_by(County) %>%
  summarise(mk = list(
    unclass(
      Kendall::MannKendall(gi_star)
    )
  )) %>%
  tidyr::unnest_wider(mk)

head(ehsa)
```

```{r}



```

Perfoming the emerging hotspot analysis

```{r}
ehsa<-emerging_hotspot_analysis(
  x=GDPPC_st,
  .var = "GDPPC",
  K=1,
  nism=99
)

```

```{r}
#| eval: false
ggplot(data=ehsa,
       aes(x=classification))+
  geom_bar

```

not all is statistic significant. to use the p- value to do it

EHSA

```{r}
hunan_ehsa <- hunan %>%
  left_join(ehsa, by = join_by(County == location))
```

```{r}
ehsa_sig <- hunan_ehsa %>%
  filter(p_value < 0.05)

tmap_mode("plot")

tm_shape(hunan_ehsa) +
  tm_polygons(alpha = 0.5) +
  tm_borders(alpha = 0.5) +
tm_shape(ehsa_sig) +
  tm_fill("classification") +
  tm_borders(alpha = 0.4)
```
